# =================================================================
# Author: Awais Nazeer (ZRR Gujjar)
# Email: awaisnazeer07@gmail.com
# =================================================================
# Bakery OCR System - Docker Compose Configuration
# =================================================================

version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped 